### ISSUE TITLE
Feature/Block Request: Terminal Receive

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#690]
Not sure if the terminal on blockly is capable of taking input...  If not, can we add it and a corresponding block?

**Comment by PropGit** [comment]
@MatzElectronics - It can't yet, that's something we were saving for after first release, so now is a good time to consider it.  Thanks.

**Comment by michel-cf** [comment]
You should be able to type into the terminal, and it should be received by the Propeller. (As the terminal is a terminal emulator, this is a standard functionality)

**Comment by kgracey** [comment]
This is something we’ve all wondered about and it’s great to have it confirmed.

**Comment by PropGit** [comment]
@michel-cf - Thanks, I didn't know it supported input and transmission already.

**Comment by PropGit** [comment]
Confirmed - It does input/transmit, though there are some items we'll have to address.  I'll test more and make issues for them.

NOTE: If you see a hollow rectangle cursor, it's because the display doesn't have focus, you'll need to click on it, at which point it will be a solid cursor indicating you can enter text.

**Comment by MatzElectronics** [comment]
If this exists, we need two blocks ASAP - "Terminal receive number" and
"Terminal receive text".  Some of the initial/basic activities that
students would do with blockly would require bidirectional use of the
terminal...
I can create them, and I'll post them as soon as I can, probably this
evening.
Matt

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
@PropGit @michel-cf @kgracey @Tested, partially working.  Blocks function correctly and are able to store user input into variables, but the terminal echoes characters typed into it.   Is there a way to turn that echo off?

**Comment by PropGit** [comment]
@MatzElectronics - Since this terminal accepts input into the same place that it shows output, there won't be any indication anywhere of what the user typed unless there's an echo.  Having it display what was typed is important for times when one thinks they made a mistake and need to verify on-screen.

If there's a way to disable echo, I'd vote for the echo feature to be enabled/disabled via a checkbox on the terminal window at the user's whim.

**Comment by MatzElectronics** [comment]
It's not that - I'm for having it echo.  Currently it double-echos.  It's
quite annoying.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment]
I'm not experiencing that.  Only single instances of character I type are showing up.

What hardware are you using?

What do you have programmed into the Propeller at the time of testing?

**Comment by PropGit** [comment]
@MatzElectronics - I couldn't test because of code generation / compilation errors.

This project:
![image](https://cloud.githubusercontent.com/assets/1266318/18365231/b90865d2-75c6-11e6-99ed-48eca35453e7.png)

generates this code:
```
/* SERIAL_TERMINAL USED */
#include "simpletools.h"

char * Received;
int RecvdNumber;



int main()
    {

        print(("Enter text:"));
        getStr(Received, 64);
        print(("Enter a number:"));
        scan("%d
            ", &RecvdNumber);
            print(Received); print("\n"); print("%d\n", RecvdNumber);

        }
```
which generates these errors:
> Required libraries: simpletools
> Library compile order: None needed
> single.c: In function 'main':
> single.c:15:14: warning: missing terminating " character [enabled by default]
> single.c:15:9: error: missing terminating " character
> single.c:16:13: warning: missing terminating " character [enabled by default]
> single.c:16:13: error: missing terminating " character
> single.c:17:28: error: expected ')' before ';' token
> single.c:19:9: warning: passing argument 1 of 'scan' makes pointer from integer without a cast [enabled by default]
> /opt/parallax/Workspace/Learn/Simple Libraries/TextDevices/libsimpletext/simpletext.h:318:5: note: expected 'const char *' but argument is of type 'int'
> single.c:19:9: error: expected ';' before '}' token

**Comment by MatzElectronics** [comment]
@PropGit @michel-cf I dove into the SimpleLibrary for the getStr() currently used.  I used getStr because scan didn't seem to work well/at all.  An underlying function inside of getStr() is generating an echo - I think that's where the double echo is coming from.  If you are in the SimpleIDE terminal, and you try to type, nothing happens - echo must be off by default, and the functions generate it instead.

I guess there are some decisions to be made on how best to handle this...should SimpleIDE be changed, or should blockly's terminal be changed, or is there a good workaround?

**Comment by PropGit** [comment]
@MatzElectronics - Thanks.  That must be part of what @AndyLindsay found that we need to address.  For now, the repairs you made should fix it.

New updates in Demo after 1:45 pm.

**Comment by MatzElectronics** [comment]
Maybe, not entirely sure, though - I can understand why the Terminal in simpleIDE does what it does.  The way it's set up now, it only echos when a scan is happening - that's probably intentional, and maybe worth doing here as well.

**Comment by MatzElectronics** [comment]
The easy fix would be to turn off local echo on the Blockly terminal, although I have no idea how easy that actually is :)

**Comment by MatzElectronics** [comment]
Weird terminal behavior notwithstanding, tested and verified.

**Comment by MatzElectronics** [comment]
Still not working.  This needs to be resolved either by removing echoing in the getStr function in Simple Libraries, OR turning off echoing in the terminal.  One thing that could be done in Simple Libraries is a fix that @AndyLindsay suggested for something else - create a function that sets a variable that turns off echoing in the getStr() function, and call that function as a setup in Blockly.  @PropGit thoughts?

**Comment by PropGit** [comment]
I prefer to solve it in Simple Libraries (since it's the culprit anyway) and I like Andy's idea of a user-settable state to make the change.

**Comment by MatzElectronics** [comment]
A candidate fix will propagate in with a minor change to the SimpleLibraries BlocklyProp branch.  @zfi and I commented out code that causes \r's to be injected and characters to be echoed by the Prop in that branch of SimpleLibraries as a temporary fix.  @AndyLindsay and I are working on a more permanent solution to be deployed down the road.  @zfi is working on automating the compilation of the libraries - which should make tweaking them a little easier.

**Comment by MatzElectronics** [comment]
This is "patched" pending a better implementation in SimpleLibraries - it's working-ish for now in Blockly.  I'm going to close it out as it's tested and verified.  The only functionality lost is the backspace, which can be restored by uncommenting a couple of lines in the blockly branch of simple libraries.  @zfi I can show you which ones, but I'm a little concerned about how it would actually function, as opposed to just telling the user, sorry, you can't use backspace in the terminal right now..
